apiVersion: hybridcloud.maibornwolff.de/v1alpha1
kind: PostgreSQLServer
metadata:
  name: demo
spec:
  version: latest
  size:
    class: small
    storageGB: 100
  credentialsSecret: demo-postgres-credentials
---
apiVersion: hybridcloud.maibornwolff.de/v1alpha1
kind: PostgreSQLDatabase
metadata:
  name: demoservice
spec:
  serverRef:
    name: demo
  database:
    charset: UTF8
  credentialsSecret: demoservice-postgres-credentials
