apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoservice
spec:
  replicas: {{.Values.serviceReplicas}}
  selector:
    matchLabels:
      app: demoservice
  template:
    metadata:
      labels:
        app: demoservice
    spec:
      containers:
      - name: demoservice
        image: swoehrl/dummy-flask:v1.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 32Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
